In [1]:
import pandas as pd


In [2]:
df=pd.DataFrame({
              
    'col1':[1,2,3,4,5],
    'col2':[12,24,36,48,60],
    'col3':"sudhanshu kumar krish ineuron one".split()
              
})

In [3]:
df['col4']=df['col1']**2

In [4]:
df

col1  col2       col3  col4
0     1    12  sudhanshu     1
1     2    24      kumar     4
2     3    36      krish     9
3     4    48    ineuron    16
4     5    60        one    25

In [5]:
df['col5']=df['col3'].str[0]

In [6]:
df

col1  col2       col3  col4 col5
0     1    12  sudhanshu     1    s
1     2    24      kumar     4    k
2     3    36      krish     9    k
3     4    48    ineuron    16    i
4     5    60        one    25    o

In [7]:
def test(a):
    return a**2

In [8]:
df['col4_2']=df['col1'].apply(test)

In [9]:
df

col1  col2       col3  col4 col5  col4_2
0     1    12  sudhanshu     1    s       1
1     2    24      kumar     4    k       4
2     3    36      krish     9    k       9
3     4    48    ineuron    16    i      16
4     5    60        one    25    o      25

In [10]:
def test2(b):
    if b=="s":
        return "s"
    else:
        return "z"

In [11]:
df['col6']=df['col5'].apply(test2)

In [12]:
df

col1  col2       col3  col4 col5  col4_2 col6
0     1    12  sudhanshu     1    s       1    s
1     2    24      kumar     4    k       4    z
2     3    36      krish     9    k       9    z
3     4    48    ineuron    16    i      16    z
4     5    60        one    25    o      25    z

In [13]:
df['col7']=df['col3'].apply(len)

In [14]:
df

col1  col2       col3  col4 col5  col4_2 col6  col7
0     1    12  sudhanshu     1    s       1    s     9
1     2    24      kumar     4    k       4    z     5
2     3    36      krish     9    k       9    z     5
3     4    48    ineuron    16    i      16    z     7
4     5    60        one    25    o      25    z     3

In [15]:
import math

In [16]:
df['col8']=df['col2'].apply(math.log)

In [17]:
df

col1  col2       col3  col4 col5  col4_2 col6  col7      col8
0     1    12  sudhanshu     1    s       1    s     9  2.484907
1     2    24      kumar     4    k       4    z     5  3.178054
2     3    36      krish     9    k       9    z     5  3.583519
3     4    48    ineuron    16    i      16    z     7  3.871201
4     5    60        one    25    o      25    z     3  4.094345

In [18]:
import numpy as np

In [19]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [20]:
a1=np.array([[2,4],[4,5]])
a1

array([[2, 4],
       [4, 5]])

In [21]:
b=np.array([1,2,3,4,5], ndmin=4)

In [22]:
b

array([[[[1, 2, 3, 4, 5]]]])

In [23]:
b[0][0][0][1]

2

In [24]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [25]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [26]:
np.asanyarray(np.mat([1, 2, 3, 4, 5]))

matrix([[1, 2, 3, 4, 5]])

In [27]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.mat(np.fromfunction(lambda i,j:i*j,(4,4),dtype="int"))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [29]:
np.fromfunction(lambda i,j,z:i*j*z,(3,3,2),dtype="int")

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [30]:
np.fromfunction(lambda i,j,z,p:i*j*z*p,(4,3,2,2),dtype="int")

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [31]:
a=np.fromfunction(lambda i,j:i*j,(3,2),dtype="int")

In [32]:
a.shape

(3, 2)

In [33]:
a.size

6

In [34]:
a.ndim

2

In [35]:
a.dtype

dtype('int32')

#### converting matrix into dataframe

In [36]:
#for 2 dimensional array

In [37]:
pd.DataFrame(a)

0  1
0  0  0
1  0  1
2  0  2

In [38]:
np.random.rand(4,9)

array([[0.29966147, 0.50899782, 0.97280019, 0.49580051, 0.32420763,
        0.77479837, 0.36132243, 0.05264797, 0.50079673],
       [0.75364623, 0.96322977, 0.8069418 , 0.98105445, 0.73771162,
        0.57512554, 0.40578338, 0.33367073, 0.43496055],
       [0.29628305, 0.51398094, 0.54039822, 0.75717942, 0.53886401,
        0.57987743, 0.5610288 , 0.18269642, 0.91926762],
       [0.02482342, 0.83454782, 0.55806755, 0.03116547, 0.1499445 ,
        0.14666391, 0.55904833, 0.37226892, 0.54380003]])

In [39]:
np.random.randint(4,9)

8

In [40]:
np.random.randn(4,9)

array([[ 0.23358467,  0.32314866, -1.31334551, -2.36923562,  0.40088575,
         0.08058923, -0.42445699, -1.37664412, -0.16863004],
       [ 1.6787281 , -1.02804611,  1.01675246,  0.26396869,  1.06373055,
         1.19989625,  1.28968773,  0.87949779, -1.20607544],
       [ 1.11118545, -0.69013291,  0.45408208, -0.12344267, -1.16297588,
         0.98547381,  0.90794691, -0.72698887, -0.25429103],
       [ 0.82510025, -0.73977639, -0.21015426, -1.35092701, -0.63015613,
        -0.29273192, -0.81427259,  0.60129529,  0.96175192]])

In [42]:
a.reshape(2,3)

array([[0, 0, 0],
       [1, 0, 2]])

In [45]:
list[range(4,10,.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [53]:
a1=np.arange(4,10.5,.2)
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [54]:
a1[1:5]

array([4.2, 4.4, 4.6, 4.8])

In [55]:
arr=np.random.rand(4,5)

In [56]:
arr

array([[0.0778462 , 0.90800469, 0.61281128, 0.11405426, 0.15624851],
       [0.61551277, 0.00320295, 0.43156795, 0.33496294, 0.55740238],
       [0.34585424, 0.26770131, 0.83462271, 0.0905706 , 0.30611949],
       [0.12020987, 0.79295751, 0.63832193, 0.30436437, 0.17994412]])

In [57]:
arr>0.5

array([[False,  True,  True, False, False],
       [ True, False, False, False,  True],
       [False, False,  True, False, False],
       [False,  True,  True, False, False]])

In [58]:
arr[arr>0.5]

array([0.90800469, 0.61281128, 0.61551277, 0.55740238, 0.83462271,
       0.79295751, 0.63832193])

In [63]:
arr[[1,2],[2]]

array([0.83462271, 0.83462271])

In [65]:
np.random.rand(8,5)

array([[0.78550167, 0.54669828, 0.12363052, 0.56240369, 0.52845575],
       [0.38104214, 0.16566171, 0.77328524, 0.63335559, 0.69520393],
       [0.3574401 , 0.46799711, 0.75497113, 0.00442082, 0.9886749 ],
       [0.7994126 , 0.91862119, 0.02021083, 0.62015977, 0.62097581],
       [0.9266592 , 0.77152363, 0.40880924, 0.30858629, 0.82762301],
       [0.68765803, 0.00404243, 0.1369513 , 0.4014703 , 0.28699283],
       [0.02774626, 0.40121606, 0.85909301, 0.27917709, 0.92761081],
       [0.34879704, 0.63203553, 0.50629741, 0.99888557, 0.10150426]])

In [68]:
arr[1:8,0:3]

array([[0.61551277, 0.00320295, 0.83462271],
       [0.34585424, 0.26770131, 0.83462271],
       [0.12020987, 0.79295751, 0.63832193]])

In [73]:
a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])

In [75]:
a*b#element wise operation

array([[ 3,  8],
       [15, 24]])

In [81]:
m=a@b#multiplication

In [83]:
m/0........................................................

SyntaxError: invalid syntax (1393144769.py, line 1)